import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1781587471695 implements MigrationInterface {
    name = 'InitialSchema1781587471695'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."queue_tickets_status_enum" AS ENUM('waiting', 'called', 'in_progress', 'done', 'skipped')`);
        await queryRunner.query(`CREATE TABLE "queue_tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_id" uuid NOT NULL, "department_id" uuid NOT NULL, "appointment_id" uuid, "ticket_number" integer NOT NULL, "status" "public"."queue_tickets_status_enum" NOT NULL DEFAULT 'waiting', "issued_at" TIMESTAMP NOT NULL DEFAULT now(), "called_at" TIMESTAMP, CONSTRAINT "REL_0c3d5c1296959eb6a1c000c847" UNIQUE ("appointment_id"), CONSTRAINT "PK_1b903aa90bcc04136caa6540c55" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."appointments_status_enum" AS ENUM('pending', 'confirmed', 'cancelled', 'completed', 'no_show')`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_id" uuid NOT NULL, "department_id" uuid NOT NULL, "doctor_id" uuid, "visit_id" uuid, "scheduled_at" TIMESTAMP NOT NULL, "status" "public"."appointments_status_enum" NOT NULL DEFAULT 'pending', "notes" text, CONSTRAINT "REL_e99a186016ddb879dfbce84606" UNIQUE ("visit_id"), CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_items_item_type_enum" AS ENUM('exam_fee', 'lab_service', 'medication')`);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "item_type" "public"."invoice_items_item_type_enum" NOT NULL, "ref_id" uuid NOT NULL, "description" character varying NOT NULL, "unit_price" numeric(12,2) NOT NULL, "quantity" integer NOT NULL, "subtotal" numeric(12,2) NOT NULL, CONSTRAINT "PK_53b99f9e0e2945e69de1a12b75a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('cash', 'bank_transfer')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "cashier_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "method" "public"."payments_method_enum" NOT NULL, "reference_code" character varying, "paid_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'pending', 'paid', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "visit_id" uuid NOT NULL, "patient_id" uuid NOT NULL, "total_amount" numeric(12,2) NOT NULL, "insurance_covered" numeric(12,2) NOT NULL DEFAULT '0', "patient_pays" numeric(12,2) NOT NULL, "prepaid_amount" numeric(12,2) NOT NULL DEFAULT '0', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."beds_status_enum" AS ENUM('available', 'occupied', 'maintenance')`);
        await queryRunner.query(`CREATE TABLE "beds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "bed_code" character varying NOT NULL, "room_code" character varying NOT NULL, "status" "public"."beds_status_enum" NOT NULL DEFAULT 'available', CONSTRAINT "UQ_2fd8630f430d3aa40cd8e0cf7e4" UNIQUE ("bed_code"), CONSTRAINT "PK_2212ae7113d85a70dc65983e742" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."admissions_status_enum" AS ENUM('active', 'discharged', 'transferred')`);
        await queryRunner.query(`CREATE TABLE "admissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_id" uuid NOT NULL, "bed_id" uuid NOT NULL, "doctor_id" uuid NOT NULL, "department_id" uuid NOT NULL, "admitted_at" TIMESTAMP NOT NULL DEFAULT now(), "discharged_at" TIMESTAMP, "status" "public"."admissions_status_enum" NOT NULL DEFAULT 'active', "notes" text, CONSTRAINT "PK_6d47682a899dfa0a78ce11fe98a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."patients_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TABLE "patients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_code" character varying NOT NULL, "full_name" character varying NOT NULL, "date_of_birth" date NOT NULL, "gender" "public"."patients_gender_enum" NOT NULL, "phone" character varying NOT NULL, "cccd" character varying, "insurance_number" character varying, "insurance_type" character varying, "address" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_72398f0b54d401540321d5db8bf" UNIQUE ("patient_code"), CONSTRAINT "PK_a7f0b9fcbb3469d5ec0b0aceaa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vital_signs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "visit_id" uuid NOT NULL, "heart_rate" double precision, "blood_pressure_sys" double precision, "blood_pressure_dia" double precision, "temperature" double precision, "respiratory_rate" double precision, "weight" double precision, "height" double precision, "spo2" double precision, "recorded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_83ba5a3455279f645885c327bb6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lab_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "service_type" character varying NOT NULL, "department_id" uuid NOT NULL, "price" numeric(12,2) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_cf2262de647feac5d441f688239" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lab_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "approved_by" uuid, "result_text" text, "image_path" character varying, "unit" character varying, "reference_range" character varying, "recorded_at" TIMESTAMP NOT NULL DEFAULT now(), "approved_at" TIMESTAMP, CONSTRAINT "REL_500778438e2e6d443a2064c8e8" UNIQUE ("order_id"), CONSTRAINT "PK_4f1c5b3b5813c98fb531e5db738" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lab_orders_status_enum" AS ENUM('ordered', 'received', 'in_progress', 'approved')`);
        await queryRunner.query(`CREATE TABLE "lab_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "visit_id" uuid NOT NULL, "doctor_id" uuid NOT NULL, "service_id" uuid NOT NULL, "status" "public"."lab_orders_status_enum" NOT NULL DEFAULT 'ordered', "notes" text, "ordered_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a488d533e758e6ba02958198f1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dispense_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "prescription_id" uuid NOT NULL, "batch_id" uuid NOT NULL, "prescription_item_id" uuid NOT NULL, "dispensed_by" uuid NOT NULL, "quantity_dispensed" integer NOT NULL, "dispensed_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_432a1c80556da359faa4be78836" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drug_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "medication_id" uuid NOT NULL, "batch_number" character varying NOT NULL, "expiry_date" date NOT NULL, "quantity" integer NOT NULL, "quantity_reserved" integer NOT NULL DEFAULT '0', "unit_price" numeric(12,2) NOT NULL, CONSTRAINT "PK_59b015a9074ec16eaebaf2f4db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "medications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "brand_name" character varying NOT NULL, "active_ingredient" character varying NOT NULL, "dosage_form" character varying NOT NULL, "strength" character varying NOT NULL, "unit" character varying NOT NULL, "route" character varying NOT NULL, "byt_code" character varying, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_cdee49fe7cd79db13340150d356" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "prescription_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "prescription_id" uuid NOT NULL, "medication_id" uuid NOT NULL, "dosage" character varying NOT NULL, "frequency" character varying NOT NULL, "duration_days" integer NOT NULL, "quantity" integer NOT NULL, "notes" text, CONSTRAINT "PK_6216831f49afc381b3934c9672c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."prescriptions_status_enum" AS ENUM('pending', 'dispensed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "prescriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "visit_id" uuid NOT NULL, "doctor_id" uuid NOT NULL, "status" "public"."prescriptions_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_097b2cc2f2b7e56825468188503" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "icd10_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "description_vi" character varying NOT NULL, "description_en" character varying, "category" character varying, CONSTRAINT "UQ_f455ed8ffc710ef8cf5513bf82a" UNIQUE ("code"), CONSTRAINT "PK_c274f26b6728835e3d5ee97976c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."visit_diagnoses_diagnosis_type_enum" AS ENUM('primary', 'secondary')`);
        await queryRunner.query(`CREATE TABLE "visit_diagnoses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "visit_id" uuid NOT NULL, "icd10_id" uuid NOT NULL, "diagnosis_type" "public"."visit_diagnoses_diagnosis_type_enum" NOT NULL DEFAULT 'primary', CONSTRAINT "PK_5a2ab9280d912b2bde04125650c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."patient_visits_status_enum" AS ENUM('waiting', 'in_progress', 'pending_results', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "patient_visits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_id" uuid NOT NULL, "doctor_id" uuid, "department_id" uuid NOT NULL, "status" "public"."patient_visits_status_enum" NOT NULL DEFAULT 'waiting', "chief_complaint" character varying, "symptoms" text, "physical_exam" text, "diagnosis_note" text, "visited_at" TIMESTAMP NOT NULL DEFAULT now(), "ended_at" TIMESTAMP, CONSTRAINT "PK_5b5111a9f4a0922fb2a7d1f8e00" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."departments_type_enum" AS ENUM('clinical', 'paraclinical', 'pharmacy', 'admin')`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."departments_type_enum" NOT NULL, "description" character varying, CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('receptionist', 'doctor', 'lab_technician', 'pharmacist', 'cashier', 'manager')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "password_hash" character varying NOT NULL, "full_name" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL, "department_id" uuid, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_e23ac161d017b9a5afeb5077e53" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_45a0850792d949769ef42829af5" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_0c3d5c1296959eb6a1c000c847b" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_3330f054416745deaa2cc130700" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_8592c8a9f19602a39b5a0439972" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_4cf26c3f972d014df5c68d503d2" FOREIGN KEY ("doctor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_e99a186016ddb879dfbce84606c" FOREIGN KEY ("visit_id") REFERENCES "patient_visits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_dc991d555664682cfe892eea2c1" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_1e37fcba92c50fe4977c5371ce5" FOREIGN KEY ("cashier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_3a49ba9f4a72307190bff39d0e1" FOREIGN KEY ("visit_id") REFERENCES "patient_visits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_e3be0c11f4ce66b9b352477cb06" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "beds" ADD CONSTRAINT "FK_2923bf4b4dccc6701a2a2dd380e" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "FK_b9424c402dbd99d8e4003fd3500" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "FK_cc1827a32123f510c80266a53e4" FOREIGN KEY ("bed_id") REFERENCES "beds"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "FK_2012b52109a4ba2f682b09f5288" FOREIGN KEY ("doctor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admissions" ADD CONSTRAINT "FK_7a9f8ed2b8a36c62264d96b1c6d" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vital_signs" ADD CONSTRAINT "FK_8a05e4862abdd1805e689c0e026" FOREIGN KEY ("visit_id") REFERENCES "patient_visits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_services" ADD CONSTRAINT "FK_07c664d7d7fb2864bc69be984a1" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_results" ADD CONSTRAINT "FK_500778438e2e6d443a2064c8e84" FOREIGN KEY ("order_id") REFERENCES "lab_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_results" ADD CONSTRAINT "FK_88fc17fc1a94bff09cd21a127a1" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_orders" ADD CONSTRAINT "FK_c31614bc44d167c311b3b3ad09b" FOREIGN KEY ("visit_id") REFERENCES "patient_visits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_orders" ADD CONSTRAINT "FK_67ddcdf2806aefa07f6e9b3db8a" FOREIGN KEY ("doctor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lab_orders" ADD CONSTRAINT "FK_a93734b7949ffc423ee94a5a120" FOREIGN KEY ("service_id") REFERENCES "lab_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispense_history" ADD CONSTRAINT "FK_fa6cf26a64343f8a964b8ae3839" FOREIGN KEY ("prescription_id") REFERENCES "prescriptions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispense_history" ADD CONSTRAINT "FK_f5a6465e6679c15fd1268deba16" FOREIGN KEY ("batch_id") REFERENCES "drug_batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispense_history" ADD CONSTRAINT "FK_b333a319ffd08a49020aaeb0b4c" FOREIGN KEY ("prescription_item_id") REFERENCES "prescription_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispense_history" ADD CONSTRAINT "FK_bb13ee68073aa8562c40d5bf216" FOREIGN KEY ("dispensed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drug_batches" ADD CONSTRAINT "FK_a442c20406a7c035c5a78b2c92e" FOREIGN KEY ("medication_id") REFERENCES "medications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription_items" ADD CONSTRAINT "FK_a603d92d4a8459db5fbe45a4aea" FOREIGN KEY ("prescription_id") REFERENCES "prescriptions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription_items" ADD CONSTRAINT "FK_dcb2e6ee4fcd4f07516ea88758d" FOREIGN KEY ("medication_id") REFERENCES "medications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_a6578313f14ea989bb422597ff8" FOREIGN KEY ("visit_id") REFERENCES "patient_visits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_2d6a1941bd705056030c2b9e07d" FOREIGN KEY ("doctor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visit_diagnoses" ADD CONSTRAINT "FK_1955e04e1d695109eaf54b6423e" FOREIGN KEY ("visit_id") REFERENCES "patient_visits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visit_diagnoses" ADD CONSTRAINT "FK_eb38c31bfb39d33b05585c9b8d0" FOREIGN KEY ("icd10_id") REFERENCES "icd10_codes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_visits" ADD CONSTRAINT "FK_906db448e7af552e4b036ca8a54" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_visits" ADD CONSTRAINT "FK_be6086d22d6452bd7719fc6c0de" FOREIGN KEY ("doctor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_visits" ADD CONSTRAINT "FK_61c123175dc579375e70ff99492" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_0921d1972cf861d568f5271cd85" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_0921d1972cf861d568f5271cd85"`);
        await queryRunner.query(`ALTER TABLE "patient_visits" DROP CONSTRAINT "FK_61c123175dc579375e70ff99492"`);
        await queryRunner.query(`ALTER TABLE "patient_visits" DROP CONSTRAINT "FK_be6086d22d6452bd7719fc6c0de"`);
        await queryRunner.query(`ALTER TABLE "patient_visits" DROP CONSTRAINT "FK_906db448e7af552e4b036ca8a54"`);
        await queryRunner.query(`ALTER TABLE "visit_diagnoses" DROP CONSTRAINT "FK_eb38c31bfb39d33b05585c9b8d0"`);
        await queryRunner.query(`ALTER TABLE "visit_diagnoses" DROP CONSTRAINT "FK_1955e04e1d695109eaf54b6423e"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_2d6a1941bd705056030c2b9e07d"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_a6578313f14ea989bb422597ff8"`);
        await queryRunner.query(`ALTER TABLE "prescription_items" DROP CONSTRAINT "FK_dcb2e6ee4fcd4f07516ea88758d"`);
        await queryRunner.query(`ALTER TABLE "prescription_items" DROP CONSTRAINT "FK_a603d92d4a8459db5fbe45a4aea"`);
        await queryRunner.query(`ALTER TABLE "drug_batches" DROP CONSTRAINT "FK_a442c20406a7c035c5a78b2c92e"`);
        await queryRunner.query(`ALTER TABLE "dispense_history" DROP CONSTRAINT "FK_bb13ee68073aa8562c40d5bf216"`);
        await queryRunner.query(`ALTER TABLE "dispense_history" DROP CONSTRAINT "FK_b333a319ffd08a49020aaeb0b4c"`);
        await queryRunner.query(`ALTER TABLE "dispense_history" DROP CONSTRAINT "FK_f5a6465e6679c15fd1268deba16"`);
        await queryRunner.query(`ALTER TABLE "dispense_history" DROP CONSTRAINT "FK_fa6cf26a64343f8a964b8ae3839"`);
        await queryRunner.query(`ALTER TABLE "lab_orders" DROP CONSTRAINT "FK_a93734b7949ffc423ee94a5a120"`);
        await queryRunner.query(`ALTER TABLE "lab_orders" DROP CONSTRAINT "FK_67ddcdf2806aefa07f6e9b3db8a"`);
        await queryRunner.query(`ALTER TABLE "lab_orders" DROP CONSTRAINT "FK_c31614bc44d167c311b3b3ad09b"`);
        await queryRunner.query(`ALTER TABLE "lab_results" DROP CONSTRAINT "FK_88fc17fc1a94bff09cd21a127a1"`);
        await queryRunner.query(`ALTER TABLE "lab_results" DROP CONSTRAINT "FK_500778438e2e6d443a2064c8e84"`);
        await queryRunner.query(`ALTER TABLE "lab_services" DROP CONSTRAINT "FK_07c664d7d7fb2864bc69be984a1"`);
        await queryRunner.query(`ALTER TABLE "vital_signs" DROP CONSTRAINT "FK_8a05e4862abdd1805e689c0e026"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "FK_7a9f8ed2b8a36c62264d96b1c6d"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "FK_2012b52109a4ba2f682b09f5288"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "FK_cc1827a32123f510c80266a53e4"`);
        await queryRunner.query(`ALTER TABLE "admissions" DROP CONSTRAINT "FK_b9424c402dbd99d8e4003fd3500"`);
        await queryRunner.query(`ALTER TABLE "beds" DROP CONSTRAINT "FK_2923bf4b4dccc6701a2a2dd380e"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_e3be0c11f4ce66b9b352477cb06"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_3a49ba9f4a72307190bff39d0e1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_1e37fcba92c50fe4977c5371ce5"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_dc991d555664682cfe892eea2c1"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_e99a186016ddb879dfbce84606c"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_4cf26c3f972d014df5c68d503d2"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_8592c8a9f19602a39b5a0439972"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_3330f054416745deaa2cc130700"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_0c3d5c1296959eb6a1c000c847b"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_45a0850792d949769ef42829af5"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_e23ac161d017b9a5afeb5077e53"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TYPE "public"."departments_type_enum"`);
        await queryRunner.query(`DROP TABLE "patient_visits"`);
        await queryRunner.query(`DROP TYPE "public"."patient_visits_status_enum"`);
        await queryRunner.query(`DROP TABLE "visit_diagnoses"`);
        await queryRunner.query(`DROP TYPE "public"."visit_diagnoses_diagnosis_type_enum"`);
        await queryRunner.query(`DROP TABLE "icd10_codes"`);
        await queryRunner.query(`DROP TABLE "prescriptions"`);
        await queryRunner.query(`DROP TYPE "public"."prescriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "prescription_items"`);
        await queryRunner.query(`DROP TABLE "medications"`);
        await queryRunner.query(`DROP TABLE "drug_batches"`);
        await queryRunner.query(`DROP TABLE "dispense_history"`);
        await queryRunner.query(`DROP TABLE "lab_orders"`);
        await queryRunner.query(`DROP TYPE "public"."lab_orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "lab_results"`);
        await queryRunner.query(`DROP TABLE "lab_services"`);
        await queryRunner.query(`DROP TABLE "vital_signs"`);
        await queryRunner.query(`DROP TABLE "patients"`);
        await queryRunner.query(`DROP TYPE "public"."patients_gender_enum"`);
        await queryRunner.query(`DROP TABLE "admissions"`);
        await queryRunner.query(`DROP TYPE "public"."admissions_status_enum"`);
        await queryRunner.query(`DROP TABLE "beds"`);
        await queryRunner.query(`DROP TYPE "public"."beds_status_enum"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_items_item_type_enum"`);
        await queryRunner.query(`DROP TABLE "appointments"`);
        await queryRunner.query(`DROP TYPE "public"."appointments_status_enum"`);
        await queryRunner.query(`DROP TABLE "queue_tickets"`);
        await queryRunner.query(`DROP TYPE "public"."queue_tickets_status_enum"`);
    }

}
